Add basic read and write functionality
RezenkovD/cost-accounting pull request #2
Opened 2022-10-03 07:22 UTC by RezenkovD

2022-10-03 07:55 UTC, qqlexa commented on sql_app/crud.py
> +from sqlalchemy.orm import Session
Why do we name `sql_app` instead just `app`?

2022-10-03 07:55 UTC, qqlexa commented on sql_app/database.py
> +Base = declarative_base()
Do we use any formatter like `Black` and others? We should leave enter on the last line.

2022-10-03 07:55 UTC, qqlexa commented on sql_app/models.py
> +    __tablename__ = "users"
Where is alembic with migrations?

2022-10-03 07:55 UTC, qqlexa commented on sql_app/models.py
> +    hashed_password = Column(String)
Is not this field `null=True`?

2022-10-03 07:55 UTC, qqlexa commented on sql_app/schemas.py
> +        orm_mode = True
Please, leave empty the last line.

2022-10-03 08:07 UTC, RezenkovD commented on sql_app/database.py
> +Base = declarative_base()
In next commit this to do fixed. Thanks

2022-10-03 08:14 UTC, RezenkovD commented on sql_app/crud.py
> +from sqlalchemy.orm import Session
Since this is sql app. And all the files are related to sql

2022-10-25 17:52 UTC, qqlexa commented on migration/versions/1bd8b34b9da0_initial.py
> +"""Initial
Migration that doesn't do anything? Well well well

2022-10-25 17:52 UTC, qqlexa commented on migration/README
> +Generic single-database configuration.
Do we need readme here?

2022-10-25 17:52 UTC, qqlexa commented on main.py
> -from fastapi import FastAPI
I hope this application can grow more and more. We should set the architecture before it will be a really big code-base.

2022-10-25 17:52 UTC, qqlexa commented on .gitignore
> +__pycache__/
It is a good practice to leave one empty line at the end.

2022-10-25 17:52 UTC, qqlexa commented on sql_app/crud.py
> +    fake_hashed_password = user.password + "notreallyhashed"
LMAO. Let's check out from https://stackoverflow.com/questions/9594125/salt-and-hash-a-password-in-python

2022-10-25 17:52 UTC, qqlexa commented on sql_app/database.py
> +PASSWORD_DB = os.getenv("PASSWORD_DB")
Better way is pydantic BaseSettings

2022-10-25 17:52 UTC, qqlexa commented on sql_app/models.py
> +    hashed_password = Column(String)
It is yet `null=True`
Warning!

2022-10-25 17:52 UTC, qqlexa commented on main.py
> +def read_items(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
Why `items` but not `goods`?
Also... maybe `items` is better for all naming variants?)

2022-10-25 17:52 UTC, qqlexa commented on main.py
> +    items = crud.get_goods(db, skip=skip, limit=limit)
Do we return goods to all users about all users? Is it correct behavior?

2022-10-25 19:16 UTC, RezenkovD commented on main.py
> -from fastapi import FastAPI
I didn't quite understand what you were talking about )

2022-10-25 19:16 UTC, RezenkovD commented on .gitignore
> +__pycache__/
Good. Thanks

2022-10-25 19:19 UTC, RezenkovD commented on main.py
> +def read_items(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
How careless I am.  Thanks.

2022-10-25 19:22 UTC, RezenkovD commented on main.py
> +    items = crud.get_goods(db, skip=skip, limit=limit)
Really. It is not necessary. At least now.

2022-10-25 19:23 UTC, RezenkovD commented on migration/README
> +Generic single-database configuration.
I think so. This is what is created during migration.

2022-10-25 19:46 UTC, RezenkovD commented on sql_app/database.py
> +PASSWORD_DB = os.getenv("PASSWORD_DB")
This was new to me. Good.

2022-10-25 19:49 UTC, RezenkovD commented on sql_app/models.py
> +    hashed_password = Column(String)
Why?I don't think so. `null == False`

2022-10-25 19:57 UTC, RezenkovD commented on sql_app/models.py
> +    __tablename__ = "users"
I add it. Thanks.

2022-10-26 06:55 UTC, RezenkovD commented on sql_app/crud.py
> +    fake_hashed_password = user.password + "notreallyhashed"
This is Rofl. This is the initial stage, it can be said as an abstraction.

2022-10-30 11:34 UTC, qqlexa requested changes

2022-10-30 11:34 UTC, qqlexa commented on alembic/env.py
> +SQLALCHEMY_DATABASE_URL = settings.SQLALCHEMY_DATABASE_URI
Why do you use it?

2022-10-30 11:34 UTC, qqlexa commented on alembic/versions/0c72ccb0d104_added_nullable_false_in_user_model.py
> +"""Added nullable=False in User model
1 PR = 1 migration

Let's remove every migration and start alembic

2022-10-30 11:34 UTC, qqlexa commented on alembic/versions/a22634b325ce_added_nullable_false_in_item_model.py
> +"""Added nullable=False in Item model
Third migration? It is bad practice

2022-10-30 11:34 UTC, qqlexa commented on crud/crud_user.py
> +    hashed_password = bcrypt.hashpw(encode_password, salt)
Great

2022-10-30 11:34 UTC, qqlexa commented on db/database.py
> +engine = create_engine(SQLALCHEMY_DATABASE_URL)
What about just settings.SQL....

2022-10-30 11:34 UTC, qqlexa commented on routers/items.py
> +from fastapi import Depends, APIRouter
Should we add routers module here (in this PR)?

2022-10-30 23:59 UTC, qqlexa requested changes

2022-10-30 23:59 UTC, qqlexa commented on config.py
> +    SQL: str
I am not sure that it is informative name

2022-10-30 23:59 UTC, qqlexa commented on routers/items.py
> +@router.post("/{user_id}/item/", response_model=schemas.item.Item)
Where can I see any test?

2022-11-01 11:20 UTC, qqlexa approved these changes

2022-11-01 15:15 UTC, merged