Add category for item
RezenkovD/cost-accounting pull request #3
Opened 2022-11-02 15:45 UTC by RezenkovD

2022-11-02 16:03 UTC, qqlexa requested changes
You should find a way to create Enums in sqlalchemy because `sa.String()` doesn't do any validation.
https://stackoverflow.com/questions/2676133/best-way-to-do-enum-in-sqlalchemy

But it can be uncomfortable for users.

2022-11-05 22:06 UTC, qqlexa requested changes

2022-11-05 22:06 UTC, qqlexa commented on crud/crud_item.py
> +    if db_item.user_id == db_item.category_id:
Let's explain me how it works? It looks strange.

I think that validation needs to be like this:
```python
users = db.query(User).join(Category, Category.user_id == User.id).filter(Category.id == db_item.category_id).all()

if len(users) == 0:
     pass # raise error and tell that it is wrong category id, Nobody from users don't have it 
elif len(users) > 1:
     pass # We will have raise here if we have not one user with select category (Business does not include this case, but we should do it)
else:
     user = next(users) # or user = users[0] because there is only one user with this category

If user.id == db_item.user_id:
     # but I am not sure why do we have it because there is also just user_id   
     Create item 
else:
    pass #  raise because not this user is owner of this category 
```

2022-11-06 09:54 UTC, RezenkovD commented on alembic/env.py
> +    from models.category import Category
I do not think so

2022-11-06 09:56 UTC, RezenkovD commented on models/category.py
> +    user_id = Column(Integer, ForeignKey("users.id"))
Thank you.

2022-11-06 09:56 UTC, RezenkovD commented on models/item.py
> +    category_id = Column(Integer, ForeignKey("categories.id"))
Thank you.

2022-11-06 09:58 UTC, RezenkovD commented on models/category.py
> +    item = relationship("Item", back_populates="category")
Thank you. Well noticed

2022-11-06 09:58 UTC, RezenkovD commented on alembic/versions/a7db2ba34f03_added_categories_table.py
> +    sa.Column('user_id', sa.Integer(), nullable=True),
This will be fixed.

2022-11-06 09:59 UTC, RezenkovD commented on alembic/versions/a7db2ba34f03_added_categories_table.py
> +    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=True))
This will be fixed.

2022-11-06 11:45 UTC, qqlexa requested changes

2022-11-06 11:45 UTC, qqlexa commented on alembic/versions/d352f1f0c26d_added_categories_table.py
> +    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
ForeignKey name is None. We should change it

2022-11-06 11:45 UTC, qqlexa commented on crud/crud_item.py
> +        if user.id == db_item.user_id:
We can do un-tab because only else block will be there

2022-11-06 11:45 UTC, qqlexa commented on models/item.py
> +import datetime # but I am not sure why do we have it because there is also just user_id
??

2022-11-06 11:45 UTC, qqlexa commented on schemas/category.py
> +    pass
Interface should be the same. Implementation can be changed to stay good interface

2022-11-06 14:35 UTC, qqlexa approved these changes

2022-11-06 14:36 UTC, merged