cost-statistics
RezenkovD/cost-accounting pull request #5
Opened 2022-11-10 19:13 UTC by RezenkovD

2022-11-11 10:32 UTC, qqlexa requested changes

2022-11-11 10:32 UTC, qqlexa commented on crud/crud_user.py
> +    return db.query(User).filter_by(id=user_id).first()
`one_or_none()` or `one()` are better

2022-11-11 10:32 UTC, qqlexa commented on crud/crud_user.py
> +    return db.query(User).filter_by(email=email).first()
`one_or_none()` or `one()` are better

2022-11-11 10:32 UTC, qqlexa commented on main.py
> +    "/users/{user_id}/statistics/{month}/{year}",
I prefer date in some str format

2022-11-11 10:32 UTC, qqlexa commented on main.py
> +    year: int = Path(gt=2021, lt=2100),
Let's use datetime module

2022-11-11 10:32 UTC, qqlexa commented on models/statistics.py
> +class Statistics:
Why do we need it?

2022-11-11 10:32 UTC, qqlexa commented on crud/crud_months_statistics.py
> +    for x in range(len(user.categories)):
`for category in user.categories`?

2022-11-11 10:32 UTC, qqlexa commented on crud/crud_months_statistics.py
> +    for x in range(number_purchases):
`for purchase in user.purchases`?

2022-11-11 10:32 UTC, qqlexa commented on crud/crud_months_statistics.py
> +    user_stats = Statistics(
Why do you use it? What about `schemas.Statistics`?

2022-11-11 10:32 UTC, qqlexa commented on crud/crud_statistics.py
> +def get_user_statistics(db: Session, user_id: int):
Duplicate function

2022-11-11 10:44 UTC, qqlexa commented on main.py
> +import schemas.statistics
Why do not import just schemas at all?

2022-11-11 10:58 UTC, RezenkovD commented on models/statistics.py
> +class Statistics:
Declared model class Statistics.

2022-11-11 10:59 UTC, RezenkovD commented on crud/crud_months_statistics.py
> +    user_stats = Statistics(
It is better to declare the class once. And pass parameters. Instead of providing values through access

2022-11-11 11:53 UTC, RezenkovD commented on crud/crud_months_statistics.py
> +    for x in range(len(user.categories)):
No. Why?

2022-11-11 11:53 UTC, RezenkovD commented on crud/crud_months_statistics.py
> +    for x in range(number_purchases):
No. Why?

2022-11-11 12:18 UTC, RezenkovD commented on main.py
> +import schemas.statistics
Good idea.

2022-11-13 19:46 UTC, qqlexa requested changes

2022-11-13 19:46 UTC, qqlexa commented on crud/crud_months_statistics.py
> +    for x in range(len(user.categories)):
Okay, I'm gonna explain :)
You use this `for loop` only for iterating by `user.categories` (it means you take `user.categories[0]`, `user.categories[1]`, `user.categories[2]` and etc.)
```python 
for x in range(len(user.categories)):
    list_categories.append(user.categories[x].title)
```
Good variant to do it in python is `for-in loop`:
```python 
for category in user.categories:
    list_categories.append(category.title)
```


Optional:
Also your variant can be useful when you use index in your code:
```python 
for x in range(len(user.categories)):
    print(f"Appending Category ({x}/{len(user.categories)})")
    list_categories.append(user.categories[x].title)
```
But you can do it with `for-in loop` as well:
```python 
for i, category in enumerate(user.categories):
    print(f"Appending Category ({i}/{len(user.categories)})")
    list_categories.append(category.title)
```

2022-11-13 19:46 UTC, qqlexa commented on crud/crud_months_statistics.py
> +    for x in range(number_purchases):
Check this thread https://github.com/RezenkovD/cost-accounting/pull/5/files#r1020092823

2022-11-13 19:46 UTC, qqlexa commented on crud/crud_months_statistics.py
> +    user_stats = Statistics(
Does not pydantic class support it?

2022-11-13 19:46 UTC, qqlexa commented on models/statistics.py
> +class Statistics:
There is already the `pydantic` class. Check the KISS rule.

2022-11-14 07:59 UTC, RezenkovD commented on crud/crud_months_statistics.py
> +    for x in range(len(user.categories)):
Ok bro, I was joking

2022-11-14 08:02 UTC, RezenkovD commented on crud/crud_months_statistics.py
> +    for x in range(number_purchases):
Here it will be redundant. not the case.

2022-11-16 09:50 UTC, qqlexa requested changes

2022-11-16 09:50 UTC, qqlexa commented on crud/crud_statistics.py
> +    user_stats = Statistics
user_stats = Statistics(email=email, ...)

2022-11-16 09:50 UTC, qqlexa commented on main.py
> +def transform_date_or_422(date_: str):
I guess it returns `-> date`?

2022-11-16 09:50 UTC, qqlexa commented on crud/crud_statistics.py
> +def get_user_statistics(db: Session, user_id: int, year_month: datetime = None):
You use only year and month, it is date. Do you need `time`? If you don't, use date instead datetime

2022-11-16 09:50 UTC, qqlexa commented on main.py
> +        db, user_id=user_id, year_month=date
You send year_month is date, func expects datetime

2022-11-16 10:07 UTC, qqlexa commented
Nice

2022-11-16 10:08 UTC, qqlexa approved these changes

2022-11-16 10:10 UTC, merged