Fix TEST SQLALCHEMY_DATABASE_URI for tests
RezenkovD/cost-accounting pull request #8
Opened 2022-11-23 16:41 UTC by qqlexa

2022-11-26 12:05 UTC, RezenkovD requested changes

2022-11-26 12:09 UTC, qqlexa commented on src/app/routers/statistics.py
>  def get_stats(user_id: int, db: Session = Depends(get_db)):
You are right. Let's change it in the future (not a requirement for this MR).

2022-11-26 12:10 UTC, qqlexa commented on tests/conftest.py
> +SQLALCHEMY_DATABASE_URI = settings.SQLALCHEMY_DATABASE_URI
Changed

2022-11-26 12:10 UTC, qqlexa commented on src/app/routers/statistics.py
> +@router.get("/{user_id}/statistics", response_model=schemas.Statistics)
Duplicated comment

2022-11-26 12:28 UTC, RezenkovD requested changes

2022-11-26 12:28 UTC, RezenkovD commented on .gitignore
> +# To ignore result of tests
Why do we need _coverage_ , etc?

2022-11-28 09:46 UTC, RezenkovD approved these changes

2022-11-28 09:46 UTC, merged